version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: clinic_admin
      POSTGRES_PASSWORD: clinic_pass
      POSTGRES_DB: clinic
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DATABASE_URL: postgres://clinic_admin:clinic_pass@db:5432/clinic
      JWT_SECRET: supersecretkey
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
