services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=basesegura1234
      - DB_NAME=meethub
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    command: npm run dev

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: basesegura1234
      MYSQL_DATABASE: meethub
    ports:
      - "3306:3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
